# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pedido.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import produto_pb2 as produto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpedido.proto\x12\x06pedido\x1a\rproduto.proto\"_\n\x06Pedido\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x13\n\x0bpreco_total\x18\x03 \x01(\x02\x12\"\n\x08produtos\x18\x04 \x03(\x0b\x32\x10.produto.Produto\"\r\n\x0bPedidoVazio\"\x1a\n\x08PedidoId\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\"/\n\x0cListaPedidos\x12\x1f\n\x07pedidos\x18\x01 \x03(\x0b\x32\x0e.pedido.Pedido2|\n\rPedidoService\x12:\n\rListarPedidos\x12\x13.pedido.PedidoVazio\x1a\x14.pedido.ListaPedidos\x12/\n\x0bObterPedido\x12\x10.pedido.PedidoId\x1a\x0e.pedido.Pedidob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pedido_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PEDIDO']._serialized_start=39
  _globals['_PEDIDO']._serialized_end=134
  _globals['_PEDIDOVAZIO']._serialized_start=136
  _globals['_PEDIDOVAZIO']._serialized_end=149
  _globals['_PEDIDOID']._serialized_start=151
  _globals['_PEDIDOID']._serialized_end=177
  _globals['_LISTAPEDIDOS']._serialized_start=179
  _globals['_LISTAPEDIDOS']._serialized_end=226
  _globals['_PEDIDOSERVICE']._serialized_start=228
  _globals['_PEDIDOSERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
