# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import pedido_pb2 as pedido__pb2


class PedidoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarPedidos = channel.unary_unary(
                '/pedido.PedidoService/ListarPedidos',
                request_serializer=pedido__pb2.PedidoVazio.SerializeToString,
                response_deserializer=pedido__pb2.ListaPedidos.FromString,
                )
        self.ObterPedido = channel.unary_unary(
                '/pedido.PedidoService/ObterPedido',
                request_serializer=pedido__pb2.PedidoId.SerializeToString,
                response_deserializer=pedido__pb2.Pedido.FromString,
                )


class PedidoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListarPedidos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PedidoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarPedidos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPedidos,
                    request_deserializer=pedido__pb2.PedidoVazio.FromString,
                    response_serializer=pedido__pb2.ListaPedidos.SerializeToString,
            ),
            'ObterPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterPedido,
                    request_deserializer=pedido__pb2.PedidoId.FromString,
                    response_serializer=pedido__pb2.Pedido.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pedido.PedidoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PedidoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarPedidos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pedido.PedidoService/ListarPedidos',
            pedido__pb2.PedidoVazio.SerializeToString,
            pedido__pb2.ListaPedidos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObterPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pedido.PedidoService/ObterPedido',
            pedido__pb2.PedidoId.SerializeToString,
            pedido__pb2.Pedido.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
