# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: produto.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduto.proto\x12\x07produto\"6\n\x07Produto\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05preco\x18\x03 \x01(\x02\"\x0e\n\x0cProdutoVazio\"\x1b\n\tProdutoId\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\"3\n\rListaProdutos\x12\"\n\x08produtos\x18\x01 \x03(\x0b\x32\x10.produto.Produto2\x87\x01\n\x0eProdutoService\x12?\n\x0eListarProdutos\x12\x15.produto.ProdutoVazio\x1a\x16.produto.ListaProdutos\x12\x34\n\x0cObterProduto\x12\x12.produto.ProdutoId\x1a\x10.produto.Produtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'produto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUTO']._serialized_start=26
  _globals['_PRODUTO']._serialized_end=80
  _globals['_PRODUTOVAZIO']._serialized_start=82
  _globals['_PRODUTOVAZIO']._serialized_end=96
  _globals['_PRODUTOID']._serialized_start=98
  _globals['_PRODUTOID']._serialized_end=125
  _globals['_LISTAPRODUTOS']._serialized_start=127
  _globals['_LISTAPRODUTOS']._serialized_end=178
  _globals['_PRODUTOSERVICE']._serialized_start=181
  _globals['_PRODUTOSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
