# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import produto_pb2 as produto__pb2


class ProdutoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarProdutos = channel.unary_unary(
                '/produto.ProdutoService/ListarProdutos',
                request_serializer=produto__pb2.ProdutoVazio.SerializeToString,
                response_deserializer=produto__pb2.ListaProdutos.FromString,
                )
        self.ObterProduto = channel.unary_unary(
                '/produto.ProdutoService/ObterProduto',
                request_serializer=produto__pb2.ProdutoId.SerializeToString,
                response_deserializer=produto__pb2.Produto.FromString,
                )


class ProdutoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListarProdutos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterProduto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProdutoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarProdutos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarProdutos,
                    request_deserializer=produto__pb2.ProdutoVazio.FromString,
                    response_serializer=produto__pb2.ListaProdutos.SerializeToString,
            ),
            'ObterProduto': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterProduto,
                    request_deserializer=produto__pb2.ProdutoId.FromString,
                    response_serializer=produto__pb2.Produto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'produto.ProdutoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProdutoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarProdutos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/produto.ProdutoService/ListarProdutos',
            produto__pb2.ProdutoVazio.SerializeToString,
            produto__pb2.ListaProdutos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObterProduto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/produto.ProdutoService/ObterProduto',
            produto__pb2.ProdutoId.SerializeToString,
            produto__pb2.Produto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
