// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: helloworld.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cumprimentador_DizerOla_FullMethodName = "/helloworld.Cumprimentador/DizerOla"
)

// CumprimentadorClient is the client API for Cumprimentador service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Definição do serviço de saudação.
type CumprimentadorClient interface {
	// Envia uma saudação
	DizerOla(ctx context.Context, in *SolicitacaoOla, opts ...grpc.CallOption) (*RespostaOla, error)
}

type cumprimentadorClient struct {
	cc grpc.ClientConnInterface
}

func NewCumprimentadorClient(cc grpc.ClientConnInterface) CumprimentadorClient {
	return &cumprimentadorClient{cc}
}

func (c *cumprimentadorClient) DizerOla(ctx context.Context, in *SolicitacaoOla, opts ...grpc.CallOption) (*RespostaOla, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespostaOla)
	err := c.cc.Invoke(ctx, Cumprimentador_DizerOla_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CumprimentadorServer is the server API for Cumprimentador service.
// All implementations must embed UnimplementedCumprimentadorServer
// for forward compatibility.
//
// Definição do serviço de saudação.
type CumprimentadorServer interface {
	// Envia uma saudação
	DizerOla(context.Context, *SolicitacaoOla) (*RespostaOla, error)
	mustEmbedUnimplementedCumprimentadorServer()
}

// UnimplementedCumprimentadorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCumprimentadorServer struct{}

func (UnimplementedCumprimentadorServer) DizerOla(context.Context, *SolicitacaoOla) (*RespostaOla, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DizerOla not implemented")
}
func (UnimplementedCumprimentadorServer) mustEmbedUnimplementedCumprimentadorServer() {}
func (UnimplementedCumprimentadorServer) testEmbeddedByValue()                        {}

// UnsafeCumprimentadorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CumprimentadorServer will
// result in compilation errors.
type UnsafeCumprimentadorServer interface {
	mustEmbedUnimplementedCumprimentadorServer()
}

func RegisterCumprimentadorServer(s grpc.ServiceRegistrar, srv CumprimentadorServer) {
	// If the following call pancis, it indicates UnimplementedCumprimentadorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cumprimentador_ServiceDesc, srv)
}

func _Cumprimentador_DizerOla_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitacaoOla)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CumprimentadorServer).DizerOla(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cumprimentador_DizerOla_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CumprimentadorServer).DizerOla(ctx, req.(*SolicitacaoOla))
	}
	return interceptor(ctx, in, info, handler)
}

// Cumprimentador_ServiceDesc is the grpc.ServiceDesc for Cumprimentador service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cumprimentador_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Cumprimentador",
	HandlerType: (*CumprimentadorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DizerOla",
			Handler:    _Cumprimentador_DizerOla_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
